name: CI of ProjectWFE
    
on:
  push:
    branches:
     - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: pwd
    - run: ls
    - name: Copying files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        rm: false
        source: "public/"
        target: "${{ secrets.REMOTE_DIR }}"
        
    - name: restart web-server
      uses: garygrossgarten/github-action-ssh@release
      with:
       command: systemctl restart projectwfe.service
       host: ${{ secrets.REMOTE_HOST }}
       port: ${{ secrets.REMOTE_PORT }}
       username: ${{ secrets.REMOTE_USER }}
       passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
       privateKey: ${{ secrets.SSH_KEY}}
